name: Build and Test Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag personal-react-site:$(date +%s)
  
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Install Script
        run: npm ci
      - name: Angular install script
        run: npm install -g @angular/cli
      - name: Unit testing
        run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: 'gh-pages'
          token: ${{secrets.WORKFLOW_DEPLOY}}
      - name: Username Config
        run: git config user.name github-actions
      - name: Email Config
        run: git config user.email github-acitons@github.com
      - name: Pull main
        run: git pull origin main --rebase
      - name: Angular install script
        run: npm install
      - name: Angular install script
        run: npm install -g @angular/cli
      - name: Build
        run: ng build
      - name: Deploy
        run: ng deploy --base-href https://michaelc143.github.io/personal-angular-site/
