name: Build and Test Web App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag personal-react-site:$(date +%s)
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Npm Install Script
        run: npm ci
      - name: Angular install script
        run: npm install -g @angular/cli
      - name: Unit testing
        run: ng test --watch=false --browsers=ChromeHeadless --code-coverage
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
          ref: 'gh-pages'
      - name: Pull main
        run: git pull origin main
      - name: Deploy
        run: ng deloy --base-href https://https://michaelc143.github.io/personal-angular-site/
